[phases.setup]
nixPkgs = ["nodejs_22"]

[variables]
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[phases.install]
cmds = [
  "npm ci --prefix server --also=dev",
  "npm ci --prefix client --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run prisma:generate --prefix server"
]

[start]
cmd = "cd server && npm run db:deploy && npm run start"
