[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  "npm ci --prefix server",
  "npm install --prefix client --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run prisma:generate --prefix server"
]
