[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci",
  "npm ci --prefix server --also=dev",
  "npm ci --prefix client --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cd server && npm run prisma:generate",
  "cd server && npm run db:deploy"
]

[start]
cmd = "cd server && npm run start"
